drop table if exists member CASCADE;

create table member
(
    seq bigint generated by default as identity,
    userId varchar(255),
    password varchar(255),
    name varchar(255),
    email varchar(255),
    primary key (seq)
);

drop table if exists article CASCADE;

create table article
(
    id bigint generated by default as identity,
    writer varchar(255),
    title varchar(255),
    content varchar(255),
    primary key (id)
);
