drop table if exists member CASCADE;

create table member
(
    seq bigint generated by default as identity,
    userId varchar(255),
    password varchar(255),
    name varchar(255),
    email varchar(255),
    primary key (seq)
);
